module.exports.categoriescontroller = require("./categories.controller")
module.exports.subcategoriescontroller = require("./subcategoris.controller")
module.exports.productsController = require("./products.controller")
module.exports.salespeopleController = require("./salespeople.controller")
// module.exports.variantscontroller = require("./variants.controller")